project:
  type: website
  output-dir: docs
  resources:
    - "images/twitter-card.png"
    - "course-materials/_slides/"
    
website:
  page-navigation: true
  title: "CS112 - Data Structures"
  description: "CS112 will teach students to use C++ for creating data structures."
  site-url: "https://ericaraujo.com/24fa-cs112"

  favicon: ./images/cs112-logo.png
  
  repo-url: https://github.com/ericaraujophd/24fa-cs112
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@ericfaraujo"
    image: "/images/twitter-card.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#A7D5E8"
    right:
    - text: "License"
      href: LICENSE.md
    - text: "Code of Conduct"
      href: CODE_OF_CONDUCT.md

  navbar:
    background: "#A7D5E8"
    logo: "images/cs112-logo.png"
    align: center
    title: false
    collapse-below: lg
 
    right:
      - icon: github
        href: https://github.com/ericaraujophd/24fa-cs112
        aria-label: GitHub
      # - icon: cloud-fill
      #   href: https://rstudio.cloud/spaces/1655/join?access_code=5rdjusfIYF5iI0Gum2vNsBDLdtdnIEELBkf2EivK
      #   aria-label: RStudio Cloud

    left:
      - text: "Overview"
        href: index.qmd
      - text: "Course Policies"
        href: policies.qmd
      - text: "Content"
        href: content.qmd
      - text: "Extras"
        href: extras.qmd

  sidebar:
    - id: policies
      title: "Course Policies"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: policies.qmd
        - href: instructors.qmd

    - id: content
      title: "Content"
      contents:
        - href: content.qmd
        - href: weekly-activities/week03.qmd
        - href: weekly-activities/week04.qmd
        - href: weekly-activities/week05.qmd
        # - href: weekly-activities/week06.qmd

    - id: extras
      title: "Extras"
      contents:
        - href: extras.qmd
        - href: 03-version-control.qmd
        - href: 03-discussion.qmd

format:
  html:
    theme:
      light: [cosmo, style/dsbox.scss]
      dark: [cosmo, style/dsbox.scss, style/dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    include-in-header: "style/fontawesome.html"

freeze: auto

editor: visual


